Repository Requisitos-de-Software/2023.1-Simplenote, pull requests merged in 2023-05, with the labels that each got.

#29 23 entrevista
  docs/elicitacao/entrevista.md
  docs/entregas.md
Labels: documentation, Revisão, Escrita

#31 #30 Storytelling
  docs/elicitacao/storytelling.md
Labels: documentation, Revisão

#36 Brainstorming
  docs/elicitacao/brainstorming.md
  mkdocs.yml
Labels: Revisão

#37 25 - Priorização
  docs/elicitacao/Priorização/FirstthingsFirst.md
  docs/elicitacao/Priorização/ThreeLevelScale.md
Labels: Revisão, Entrega

#45 41 especificacao suplementar
  docs/modelagem/especificacao_suplementar.md
  mkdocs.yml
Labels: documentation, Revisão, Escrita

#55 46 - User Story
  docs/modelagem/User_story.md
Labels: documentation, Revisão, Entrega

#57 49 ajuste de feedbacks entrega 2
  docs/elicitacao/Priorização/FirstthingsFirst.md
  docs/elicitacao/Priorização/MoScoW.md
  docs/elicitacao/Priorização/ThreeLevelScale.md
  docs/elicitacao/brainstorming.md
  docs/elicitacao/entrevista.md
  docs/elicitacao/personas.md
  docs/elicitacao/questionario.md
  docs/elicitacao/storytelling.md
  docs/pré-rastreabilidade/RichPictureSimpleNoteV3.0.drawio.png
Labels: documentation, Revisão, Correção, Ajustes

#56 38 casos de uso
  docs/img/ator-usecase.png
  docs/img/caso-de-uso-usecase.png
  docs/img/comunicacao-usecase.png
  docs/img/diagrama-UC.png
  docs/img/sistema-usecase.png
  docs/modelagem/casos_de_uso.md
Labels: Revisão
